;
; Object diffusion mini-protocol
;

objectDiffusion2Message
    = msgInit
    ; corresponds to either MsgRequestObjIdsBlocking or
    ; MsgRequestObjIdsNonBlocking in the spec
    / msgRequestObjIds
    / msgReplyObjIds
    / msgRequestObjs
    / msgReplyObjs
    / msgDone

; Parameters of the protocol:
;
; - initialPayload
; - object
; - id
; - objectIds (they will be turned into *id with a function responseToIds)

msgInit          = [0, initialPayload]
msgRequestObjIds = [1, blocking, objCount, objCount]
msgReplyObjIds   = [2, objectIds ]
msgRequestObjs   = [3, *id ]
msgReplyObjs     = [4, *object ]
msgDone          = [5]

blocking         = false / true
objCount         = word16
