version: "0.5"

processes:
  setup:
    command: "${TESTNET_CMD} setup"

  cardano-testnet:
    command: "${TESTNET_CMD} start-local-testnet"
    depends_on:
      setup:
        condition: process_completed_successfully
    readiness_probe:
      exec:
        # NOTE: devnet-env is hardcoded here.
        # TODO: Add an endpoint in testnet to health check testnet
        command: "[ -S ./devnet-env/socket/node1/sock ]"
      initial_delay_seconds: 1
      period_seconds: 1
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 60

  get-node-tips:
    command: "${TESTNET_CMD} get-node-tips"
    disabled: true

  add-toxicity:
    command: "${TESTNET_CMD} add-toxicity"
    disabled: true

  remove-toxicity:
    command: "${TESTNET_CMD} remove-toxicity"
    disabled: true

  sync-nodes:
    command: "${TESTNET_CMD} sync-nodes"
    depends_on:
      toxiproxy-server:
        condition: process_healthy

  toxiproxy-server:
    command: "${TESTNET_CMD} toxiproxy-server"
    depends_on:
      cardano-testnet:
        condition: process_healthy
    readiness_probe:
      exec:
        command: "curl -sf http://127.0.0.1:8474/proxies"
      initial_delay_seconds: 1
      period_seconds: 2
      timeout_seconds: 1
      success_threshold: 1
      failure_threshold: 5
